version: '3.8'

services:
  proxy:
    image: dejan1998/socketio-chat-app-proxy
  client:
    image: dejan1998/socketio-chat-app-client
    environment:
      - NEXT_PUBLIC_SOCKET_URL=139.177.186.174:4000
  server1:
    image: dejan1998/socketio-chat-app-server
  server2:
    image: dejan1998/socketio-chat-app-server
  server3:
    image: dejan1998/socketio-chat-app-server

# How to get IP Address:
# $ ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
