version: '3.8'

x-server: &x-server
  depends_on:
    - redis
  ports:
    - 4000:4000

services:
  client:
    depends_on:
      - server
    ports:
      - 3000:3000
  server:
    <<: *x-server
  redis:
    image: redis:6.2.6-bullseye
    ports:
      - 6379:6379
