version: '3.8'

services:
  client:
    build: ./client
    environment:
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:4000
  proxy:
    build: ./haproxy
  server1:
    build: ./server
  server2:
    build: ./server
  server3:
    build: ./server
