version: '3.8'

x-server-local: &x-server-local
  environment:
    - COLLECTION_NAME=dev
  build:
    ./server

services:
  client:
    build: ./client
    environment:
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:4000
  proxy:
    build: ./haproxy
  server1:
    <<: *x-server-local
  server2:
    <<: *x-server-local
  server3:
    <<: *x-server-local
