apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  annotations:
    cloud.google.com/load-balancer-type: "External"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: # TODO dejan: create global static IP address on Terraform
