apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: dejan1998/socketio-chat-app-client
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SOCKET_URL
              value: '34.82.161.222'
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  loadBalancerIP: '34.82.161.222'
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
