apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  annotations:
    cloud.google.com/backend-config: chatapp-be-config
    kubernetes.io/ingress.global-static-ip-name: load-balancer-ip-address
spec:
  rules:
  - http:
      paths:
      - path: /client
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 3000
      - path: /server
        pathType: Prefix
        backend:
          service:
            name: server-service
            port:
              number: 4000
